Use Symfony LTS 4.4
BoShurik/telegram-bot-example pull request #2
Opened 2019-11-27 09:07 UTC by cybernet

https://symfony.com/releases/4.4

 End of bug fixes: November 2022

2019-11-27 09:15 UTC, BoShurik commented
Thanks for contribution
You forgot to change lock-file, as it's a project, not a library.
Also, I prefer latest (5.0.0) version of symfony

2019-11-27 09:25 UTC, cybernet commented
LTS is better, in my opinion

2019-11-27 09:29 UTC, BoShurik commented
Why? It's just an example, and is better to keep it up to date. 
People will refer to it when they want to create new project and it likely be symfony 5

2019-11-27 09:31 UTC, cybernet commented
3.4 is still being used because it's LTS, even some use 2.8 for the same reason

2019-11-27 09:55 UTC, BoShurik requested changes

2019-11-27 09:55 UTC, BoShurik commented on composer.json
>          "boshurik/telegram-bot-bundle": "^3.1",
Please add ^4.0 version of the bundle

2019-11-27 09:55 UTC, BoShurik commented on composer.json
>          "symfony/framework-bundle": "4.2.*",
Must be `4.4.*`

2019-11-28 00:27 UTC, cybernet commented
> 
> 
> Thanks for contribution
> You forgot to change lock-file, as it's a project, not a library.
> Also, I prefer latest (5.0.0) version of symfony

Then you should also use EventSubscriberInterface instead of Event :)

2019-11-28 08:48 UTC, BoShurik commented
> Then you should also use EventSubscriberInterface instead of Event :)

Do you mean changed signature of EventSubscriberInterface? Yes, it's not just update version constraints. It would be great to fix all deprecations in 4.4

2020-06-20 12:26 UTC, BoShurik commented
Updates to 5.1 in 4a7a61d

2020-06-20 12:26 UTC, closed without merging